### ISSUE TITLE
PXSX boot issue on boot

### ISSUE THREAD

**Issue by kitkatclap** [M69W/XPS-15-9570-macOS#1]
I tried using your efi, as my xps has the same specs. Sadly the laptop never boots and hangs waiting on PXSX, which i believe means the gpu isnt loading.

I was wondering what bios version you were on, as it may explain why your config won't work on my device.

**Comment by M69W** [comment]
I'm sorry for the necessary information the machine need.

My Laptop:
XPS 9570 i5 8300h 1080P DW1560
BIOS 1.7
[BIOS Settings](https://github.com/jardenliu/XPS15-9560-Mojave/blob/master/BIOS.md)

Installed MacOS and restart to enter the system
reconstruct kextcache:
`sudo kextcache -i /`
The Command is the key to make GPU to work.
replace the Install Clover with my Clover.


Could you need [The Install Clover](https://github.com/shenlinsl/DELL-XPS-15-9570-8950-4K-macOS-Mojave)?

I hope it's useful to you.

**Comment by prajals** [comment]
Which hard drive are you using? is it samsung pm981?

**Comment by M69W** [comment]
> Which hard drive are you using? is it samsung pm981?

970 evo, and you choose 970 PRO.
SSD pm981 to install MacOS will cause problem and I don't know how solve it.

**Comment by prajals** [comment]
Thank you for your reply. will surely go for 970 pro.

**Comment by kitkatclap** [comment]
Solved my issue. For anyone in the future the 1820A does not seem to play nicely with osX and caused my issue. Switching to the 1560/1830 fixes it. Also, I have a pm961 and it works fine to install to.
