### ISSUE TITLE
HDMI

### ISSUE THREAD

**Issue by toyinstark** [M69W/XPS-15-9570-macOS#2]
System crashes when i plug HDMi cable.

i tried using the solution provided here but its not working
https://github.com/Xigtun/xps-9570-mojave/issues/31

Also,
i tried using a USBC to Displayport cable. External monitor is detected but black screen no image.
i even tried to chnge the board-id in the smbios as suggested here:
https://github.com/Xigtun/xps-9570-mojave/issues/24

I used all these board-ids:
Mac-00BE6ED71E35EB86
Mac-031B6874CF7F642A
Mac-189A3D4F975D5FFC
Mac-27ADBB7B4CEE8E61
Mac-35C1E88140C3E6CF
Mac-4B7AC7E43945597E
Mac-77EB7D7DAF985301
Mac-7DF21CB3ED6977E5
Mac-81E3E92DD6088272
Mac-C3EC7CD22292981F
Mac-C9CF552659EA9913
Mac-FC02E91DDD3FA6A4

still no image. 
when i  change smbios to macbook 14,1 i get flickering on my external montor. The monitor displays image for one second and goes off. 

Help us fix hdmi or USBC-Displayport.

Thanks

**Comment by M69W** [comment]
Sorry , I have no HDMI device

**Comment by M69W** [comment]
[[FIX] Coffee Lake Intel UHD Graphics 630 on macOS Mojave: HDMI Output Issue [Public Testing Stage]](https://www.tonymacx86.com/threads/fix-coffee-lake-intel-uhd-graphics-630-on-macos-mojave-hdmi-output-issue-public-testing-stage.275126/)
