### ISSUE TITLE
冷启动问题

### ISSUE THREAD

**Issue by FoundTheWOUT** [M69W/XPS-15-9570-macOS#7]
用了一圈的efi，最稳定的就是你的了。但还是那个问题，不能冷启动。就像 lutettersoul里的[issue](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/54)，zyfzsi里提到的那样。必须进win再进mac才能驱动wifi。他说用bavariancake能驱动，但我用他的驱动直接连系统都进不去（无论怎么屏蔽针脚都一样）。你自己使用的时候是能冷启动的吗。

**Comment by M69W** [comment]
我已经 使用了https://github.com/xxxzc/xps15-9570-macos 的了。

触屏在使用  I2C 高版本有点问题，可以使用 这个 [SSDT](https://github.com/VoodooI2C/VoodooI2C/issues/392#issuecomment-810386204)
