### ISSUE TITLE
kernel_task疯狂写盘的问题

### ISSUE THREAD

**Issue by epnode** [M69W/XPS-15-9570-macOS#8]
机型：9570 8300H 1080p
系统：Mojave 10.14.6
更换硬件：SM981 256G-->SM961 512G
Killer 1535-->1820a
在使用您的Clover配置文件进行引导后出现kernel_task进程疯狂写盘的情况（动不动写满100G）
可能是触摸板I2C的问题？

-v后出现launchd进程一起参与写盘
![20200208-161619](https://user-images.githubusercontent.com/25266606/74081871-97c06000-4a8e-11ea-82a2-d437c69a285c.png)

**Comment by M69W** [comment]
Clover 很久没用了，现在用15.3，无法重现你的问题
不妨贴下日志看看
`log show --last boot | grep -i i2c`

推荐使用：
https://github.com/bavariancake/XPS9570-macOS
https://github.com/xxxzc/xps15-9570-macos
https://github.com/OldDream/Dell-XPS-15-9570-macOS-Mojave
