### ISSUE TITLE
Some questions (not an issue)

### ISSUE THREAD

**Issue by jaromeyer** [M69W/XPS-15-9570-macOS#9]
First, thank you for your work! I'm sorry but I'm having a hard time understanding what exactly you have changed and what is important to know because everything is in Chinese and unfortunately I don't Could you briefly explain the difference between your OC-Mod-0.5.7 and xxxcz's repo? And is the HDMI fix from 0.5.6 included too? And are there any important things about installing or commands I should know? I would really appreciate it if you would take your time to quickly answer some of my questions. And I'm pretty sure that others would profit too if there was some sort of documentation in English.

**Comment by M69W** [comment]
Thanks for your Affirmation of that. Here is my backup and also for someone who need. And I had show it's source Link on README that let someone to see what it change. As for your confusion, I just try to fix       problem I met on their  period specific version's EFI. I recommend you to use their latest release.
